import type { MetadataRoute } from "next";

const RAW_URLS: string[] = [
  "https://kathyclean.com/cleaning-services-castle-rock",
  "https://kathyclean.com/cleaning-services-centennial",
  "https://kathyclean.com/cleaning-services-denver",
  "https://kathyclean.com/cleaning-services-englewood",
  "https://kathyclean.com/cleaning-services-highlands-ranch",
  "https://kathyclean.com/cleaning-services-littleton",
  "https://kathyclean.com/cleaning-services-lone-tree",
  "https://kathyclean.com/cleaning-services-parker",
  "https://kathyclean.com/commercial-cleaning-castle-rock",
  "https://kathyclean.com/commercial-cleaning-centennial",
  "https://kathyclean.com/commercial-cleaning-denver",
  "https://kathyclean.com/commercial-cleaning-englewood",
  "https://kathyclean.com/commercial-cleaning-greenwood-village",
  "https://kathyclean.com/commercial-cleaning-highlands-ranch",
  "https://kathyclean.com/commercial-cleaning-littleton",
  "https://kathyclean.com/commercial-cleaning-lone-tree",
  "https://kathyclean.com/commercial-cleaning-parker",
  "https://kathyclean.com/house-cleaning-castle-rock",
  "https://kathyclean.com/house-cleaning-centennial",
  "https://kathyclean.com/house-cleaning-central-park",
  "https://kathyclean.com/house-cleaning-cherry-creek",
  "https://kathyclean.com/house-cleaning-cherry-hills-village",
  "https://kathyclean.com/house-cleaning-denver",
  "https://kathyclean.com/house-cleaning-englewood",
  "https://kathyclean.com/house-cleaning-glendale",
  "https://kathyclean.com/house-cleaning-greenwood-village",
  "https://kathyclean.com/house-cleaning-highlands-ranch",
  "https://kathyclean.com/house-cleaning-hilltop",
  "https://kathyclean.com/house-cleaning-ken-caryl",
  "https://kathyclean.com/house-cleaning-lakewood",
  "https://kathyclean.com/house-cleaning-littleton",
  "https://kathyclean.com/house-cleaning-lone-tree",
  "https://kathyclean.com/house-cleaning-parker",
  "https://kathyclean.com/house-cleaning-roxborough-park",
  "https://kathyclean.com/house-cleaning-sheridan",
  "https://kathyclean.com/house-cleaning-the-pinery",
  "https://kathyclean.com/house-cleaning-university-park",
  "https://kathyclean.com/house-cleaning-washington-park",
  "https://kathyclean.com/move-in-move-out-castle-rock",
  "https://kathyclean.com/move-in-move-out-centennial",
  "https://kathyclean.com/move-in-move-out-cherry-creek",
  "https://kathyclean.com/move-in-move-out-cherry-hills-village",
  "https://kathyclean.com/move-in-move-out-denver",
  "https://kathyclean.com/move-in-move-out-englewood",
  "https://kathyclean.com/move-in-move-out-glendale",
  "https://kathyclean.com/move-in-move-out-greenwood-village",
  "https://kathyclean.com/move-in-move-out-highlands-ranch",
  "https://kathyclean.com/move-in-move-out-hilltop",
  "https://kathyclean.com/move-in-move-out-ken-caryl",
  "https://kathyclean.com/move-in-move-out-lakewood",
  "https://kathyclean.com/move-in-move-out-littleton",
  "https://kathyclean.com/move-in-move-out-lone-tree",
  "https://kathyclean.com/move-in-move-out-parker",
  "https://kathyclean.com/move-in-move-out-university-park",
  "https://kathyclean.com/move-in-move-out-washington-park",
  "https://kathyclean.com/move-in-move-out-watkins",
  "https://kathyclean.com/post-construction-castle-rock",
  "https://kathyclean.com/post-construction-centennial",
  "https://kathyclean.com/post-construction-central-park",
  "https://kathyclean.com/post-construction-cherry-creek",
  "https://kathyclean.com/post-construction-cherry-hills-village",
  "https://kathyclean.com/post-construction-denver",
  "https://kathyclean.com/post-construction-englewood",
  "https://kathyclean.com/post-construction-glendale",
  "https://kathyclean.com/post-construction-greenwood-village",
  "https://kathyclean.com/post-construction-highlands-ranch",
  "https://kathyclean.com/post-construction-hilltop",
  "https://kathyclean.com/post-construction-ken-caryl",
  "https://kathyclean.com/post-construction-lakewood",
  "https://kathyclean.com/post-construction-littleton",
  "https://kathyclean.com/post-construction-lone-tree",
  "https://kathyclean.com/post-construction-parker",
  "https://kathyclean.com/post-construction-roxborough-park",
  "https://kathyclean.com/post-construction-sheridan",
  "https://kathyclean.com/post-construction-the-pinery",
  "https://kathyclean.com/post-construction-university-park",
  "https://kathyclean.com/post-construction-washington-park",
  "https://kathyclean.com/window-cleaning-castle-rock",
  "https://kathyclean.com/window-cleaning-centennial",
  "https://kathyclean.com/window-cleaning-central-park",
  "https://kathyclean.com/window-cleaning-cherry-creek",
  "https://kathyclean.com/window-cleaning-cherry-hills-village",
  "https://kathyclean.com/window-cleaning-denver",
  "https://kathyclean.com/window-cleaning-englewood",
  "https://kathyclean.com/window-cleaning-glendale",
  "https://kathyclean.com/window-cleaning-greenwood-village",
  "https://kathyclean.com/window-cleaning-highlands-ranch",
  "https://kathyclean.com/window-cleaning-hilltop",
  "https://kathyclean.com/window-cleaning-ken-caryl",
  "https://kathyclean.com/window-cleaning-lakewood",
  "https://kathyclean.com/window-cleaning-littleton",
  "https://kathyclean.com/window-cleaning-lone-tree",
  "https://kathyclean.com/window-cleaning-parker",
  "https://kathyclean.com/window-cleaning-university-park",
  "https://kathyclean.com/window-cleaning-washington-park",
  "https://kathyclean.com",
  "https://kathyclean.com/service-areas",
  "https://kathyclean.com/services/house-cleaning-and-maid-service-with-satisfaction-guarantee",
  "https://kathyclean.com/request-quote",
];

function ensureTrailingSlash(url: string): string {
  try {
    const u = new URL(url);
    if (!u.pathname.endsWith("/")) u.pathname += "/";
    u.hash = "";
    return u.toString();
  } catch {
    return url.endsWith("/") ? url : `${url}/`;
  }
}

export default function sitemap(): MetadataRoute.Sitemap {
  const urls = Array.from(new Set(RAW_URLS.map(ensureTrailingSlash)));
  const lastModified = new Date();
  return urls.map((url) => ({ url, lastModified }));
}
