export const services = [
  'house-cleaning',
  'commercial-cleaning',
  'window-cleaning',
] as const;

export const locations = [
  'denver',
  'parker',
  'castle-rock',
  'lone-tree',
  'englewood',
  'highlands-ranch',
  'centennial',
  'central-park',
  'hilltop',
  'washington-park',
  'greenwood-village',
  'littleton',
  'cherry-creek',
  'university-park',
  'highland',
  'englewood',
  'aurora',
  'lakewood',
  'littleton',
  'sheridan',
  'greenwood-village',
  'cherry-hills-village',
  'roxborough-park',
  'ken-caryl',
  'glendale',
  'bow-mar',
  'the-pinery',
  'watkins',
] as const;
